name: Farrago
favicon: null
layout_spectrum: 0.49558162363246083
typography_spectrum: 0.43114078394137323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5379812300670892
  lightness: 0.8822620862629265
  saturation: 0.07808630727231503
  rhythmicContrast: 0.011135376524180174
purpose: []
