typography_spectrum: 0.43114078394137323
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74916
analytics:
  google: null
  facebook: null
  twitter: null
name: Farrago
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Farrago
description: An Eclectic assortment of topics
purpose: []
